### ISSUE TITLE
Access to picture: URL ?

### ISSUE THREAD

**Issue by KHome** [vbessler/grafana-pictureit#16]
What is the recommendation to store a picture; 
Which folder and access right should be used? 
Currently I've tried /var/www/html
but it's not working.. How this can be debugged?

**Comment by araisch** [comment]
Local Access isn't working for me either. Http Sources are working. Any hints?

**Comment by flopp999** [comment]
I put my image in /usr/share/grafana/public/img

then in Grafana panel I put /public/img/abc.jpg

**Comment by KHome** [comment]
Perfect! Works like flopp999 posted :+1:

**Comment by Borreguin** [comment]
Hello people, I hope here is the place to put my question. In my current version of Grafana (windows Grafana v7.0.3) this approach is not working. Do you know an alternative way to achieve the same?

**Comment by brokenbrigde9000** [comment]
Same problem here, oddly enough the Grafana stock images in the /public/img/ folder actually do show up. Would love to find the solution.

-edit
I seem to have found the problem. My images refuse to load when there is a space in the filename, when removed all works fine.
