### ISSUE TITLE
Influx - No data is visible[solved]

### ISSUE THREAD

**Issue by flopp999** [vbessler/grafana-pictureit#18]
I can see data if I use built-in grafana but when I change to Influx source no data is visible.
Can it be something with my query, I tried same query with Graph and I can see data.
Can I use any Group by time?

**Comment by chappi6** [comment]
hi, I tried it with a current version of influxdb and grafana 4.6 . It was a float value. Did you specify the correct metric name?

**Comment by flopp999** [comment]
i have 5.0.3 and Influx 1.5.
what shall the metric name be, do you mean Alias name, must it be specific name to work?

**Comment by flopp999** [comment]
This is what I get
![pictureit](https://user-images.githubusercontent.com/21694965/37732636-ebc55f7e-2d45-11e8-9beb-2f17aa9dce6e.png)

**Comment by flopp999** [comment]
Thanks for helping me in the correct direction.
You need to put a name in ALIAS BY(in the query) and then put the same name in Metric name in Option tab
