### ISSUE TITLE
Plugin is no longer maintained - convert this plugin to an official plugin

### ISSUE THREAD

**Issue by xkilian** [vbessler/grafana-pictureit#26]
This is one of the plugins that has a great impact in complementing traditional dashboarding (Which grafana excels at). There are have been many improvements in branches, there are lots of great ideas for making this type of plugin great.
@torkelo - Rebrand and re-relase this plugin and make the development more open to all under the Grafana org. 
All others that have forked this, are any of you interested in becoming the maintainer? @GridProtectionAlliance  @wehcamp Anyone else?

This plugin is the only one to display complexe systems, processes and interfaces and add a layer of dynamic information on it. (Think of Nagvis, Network Weathermap) It permits us to sell Grafana to corporate management as it can mix business and operational information.

Cheers,

**Comment by 7yl4r** [comment]
@TLMiot 's [fork](https://github.com/TLMiot/grafana-pictureit) looks to have some nice improvements.

**Comment by TLMiot** [comment]
> @TLMiot 's [fork](https://github.com/TLMiot/grafana-pictureit) looks to have some nice improvements.

Please note that my fork rewrite some of the core stuff, you shoudn't upgrade the current version to mine directly

**Comment by xkilian** [comment]
This plugin is dead.
